# Generated by Django 2.2.20 on 2021-09-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'PAID'), ('SENT', 'SENT')], max_length=5, null=True, verbose_name='Status'),
        ),
    ]
