version: "3.7"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 1111:8000
    env_file:
      - ./.env.dev