# Generated by Django 2.2.20 on 2021-09-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['payment_date']},
        ),
        migrations.AlterModelOptions(
            name='paymentdetail',
            options={'ordering': ['creation_date']},
        ),
    ]
